### ISSUE TITLE
Bug in damping between wall and particle

### ISSUE THREAD

**Issue by prashjha** [prashjha/PeriDEM#14]
@yuantangjin pointed out the bug when applying damping between particle and wall

**Comment by yuantangjin** [comment]
Hi, prashant! 

I don't know what this reply email means, right. The last email I received from you is the same. Is this automatically sent by GitHub?


 I have been learning how to use github in the last few days. I'm not familar with github, not really good at branching right. I'll test as soon as prossible. And I'll open an issue in github repo on damping issues if the problem still appear. I think I can use Git now, one step closer to writing a code program.


And I downloaded the code and compiled it again. It seems that I have encountered a problem again. Test 4 takes a long time and seems to be stuck here.


I don't know what this reply email means, right. The last email I received from you is the same.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "prashjha/PeriDEM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [prashjha/PeriDEM] Bug in damping between wall and particle (#14)





 
Closed #14 via #15.
